---
title: "Features"
---

<style>
.overview-box h2 {
  margin-bottom: 20px;
}

.overview-box ul{
    margin-top: 0;
    margin-bottom: 10px;
    padding-left: 15px;
    color: #dd4814;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page gives an overview over the features currently implemented in the OpenRepGrid R package. Note that the most accurate list of features in always found in the documentation of the R package itself. We try to keep this list up-to-date though. As the package development is an ongoing process there might be forms of analysis that have not yet been implemented. If you miss any features please [make a suggestion](contribute.html) for a new feature or for an enhancement or modification of an old features here.

<div class="container overview-box">
<div class="row">

<h2>Single grids</h2>
<hr class="soften">


<div class="col-md-3">

  <!-- Basics -->
  <h3>Basics</h3>
  * [Installation](installation.html)
  * [Basic package handling](basics-manipulations.html)
  * [Settings](settings.html)
  * [Loading and saving grids](loading.html)
  
  <!-- Analyzing constructs -->
  <h3>Analyzing constructs</h3>
  * [Descriptive statistics](descriptives.html)
  * [Construct correlations](constructs-correlation.html)
  * [Distances between constructs](constructs-distances.html)
  * [PCA of construct correlations](constructs-pca.html)
  * [Cluster analysis of constructs](clustering.html)
  
</div>
  

<!-- col 2 -->
<div class="col-md-3">

  <!-- Analyzing elements -->
  <h3>Analyzing elements</h3>
  * [Descriptive statistics of elements](descriptives.html)
  * [Element correlations](elements-correlation.html)
  * [Distances between elements](elements-distances.html)
  * [Standardized elements distances](elements-distances-standardized.html)
  * [Cluster analysis of elements](clustering.html)
  
  <h3>Visualization</h3>
  * [Bertin plots](visualization-bertin.html)
  * [Biplots](visualization-biplot.html)
  
</div>
  

<div class="col-md-3">

  <h3>Index measures</h3>
  * [Intensity index](measures-intensity.html)
  * [PVAFF](measures-pvaff.html)
  * [Conflicts: based on correlations or distances](measures-conflict.html)
  * [Implicative dilemmas](measures-implicative.html)
  
  <h3>Reordering</h3>
  * [Reorder and align constructs](reordering.html)
  
  
</div>

</div>
</div>



