---
title: "Biplots"
output: 
  html_document:
    toc: true
    self_contained: no
---


```{r setup, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
options(width=120)
library(rgl)
library(OpenRepGrid)
settings(show.scale=FALSE, show.meta=FALSE)
library(knitr)
opts_chunk$set(comment=NA)
knit_hooks$set(webgl = hook_webgl)
cat('<script type="text/javascript">', 
    readLines(system.file('WebGL', 'CanvasMatrix.js', package = 'rgl')), 
    '</script>', sep = '\n')
```


```{r testgl, webgl=TRUE, fig.width=4, fig.height=4}
x <- sort(rnorm(1000))
y <- rnorm(1000)
z <- rnorm(1000) + atan2(x,y)
plot3d(x, y, z, col=rainbow(1000))
```

Hide webgl canvas when button is pressed.

```{r echo=FALSE, results='asis'}
cat(' 

<button id="mybtn" class="btn">Show/hide</button>

<script>
$( "#mybtn" ).click(function() {
  $( "#testglcanvas" ).hide();
});

 if (!window.WebGLRenderingContext) {   
    // the browser doesn\'t even know what WebGL is     
    $( "#test" ).css("color", "blue")
  } else {
    var canvas = document.getElementById("myCanvas");
    var context = canvas.getContext("webgl");
    if (!context) {
      // browser supports WebGL but initialization failed.
      $( "#test" ).css("color", "red")
    }
  }
 </script>
 ')
```