---
title: "Mailing list"
output: html_document
---

<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
#mc_embed_signup{
background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; 
  width: 400px;
  display: block;
  margin-left: auto;
  margin-right: auto;
  border: 10px solid #ccc;
  border-radius: 25px;
  padding: 20px;
  padding-bottom: 10px;
}
/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
 We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
 div.centre

</style>
<div id="mc_embed_signup">
<form action="//openrepgrid.us9.list-manage.com/subscribe/post?u=6e301501f8c1ac2241f7eb6c4&amp;id=6e56d4a541" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div id="mc_embed_signup_scroll">
<label for="mce-EMAIL">Subscribe to the OpenRepGrid mailing list</label>
<p style="color: #555; line-height: 150%;">Stay up to date with developments on OpenRepGrid. 
This is a low frequency list. There will be only very few mails per year.</p><br>
<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
<br>
<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
<div style="position: absolute; left: -5000px;"><input type="text" name="b_6e301501f8c1ac2241f7eb6c4_6e56d4a541" tabindex="-1" value=""></div>
<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</div>
</form>
</div>


<style type="text/css">
body .modal {
  width: 500px;
  /* must be half of the width, minus scrollbar on the left (30px) */
  /* margin-left: -280px; */
  border: 10px solid #ccc;
  border-radius: 25px;
}

#mc_embed_signup2{
background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; 
  width: 400px;
  display: block;
  margin-left: auto;
  margin-right: auto;
  padding: 20px;
  padding-bottom: 10px;
}
</style>


<!-- Button to trigger modal -->
<a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
  
  <h3 id="myModalLabel">Subscribe to the OpenRepGrid mailing list</h3>
</div>
<div class="modal-body">


<div id="mc_embed_signup2">
<form action="//openrepgrid.us9.list-manage.com/subscribe/post?u=6e301501f8c1ac2241f7eb6c4&amp;id=6e56d4a541" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div id="mc_embed_signup_scroll">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<label for="mce-EMAIL" hidden="true">Subscribe to the OpenRepGrid mailing list</label>
<p style="color: #555; line-height: 150%;">Stay up to date with developments on OpenRepGrid. 
This is a low frequency list. There will be only very few mails per year.</p><br>
<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
<br>
<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
<div style="position: absolute; left: -5000px;"><input type="text" name="b_6e301501f8c1ac2241f7eb6c4_6e56d4a541" tabindex="-1" value=""></div>
<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</div>
</form>
<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div>
  
</div>
<!-- <div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div> -->
</div>

<!--End mc_embed_signup-->


<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
 We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//openrepgrid.us9.list-manage.com/subscribe/post?u=6e301501f8c1ac2241f7eb6c4&amp;id=6e56d4a541" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div id="mc_embed_signup_scroll">
<h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
<label for="mce-FNAME">First Name </label>
<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
<label for="mce-LNAME">Last Name </label>
<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div id="mce-responses" class="clear">
<div class="response" id="mce-error-response" style="display:none"></div>
<div class="response" id="mce-success-response" style="display:none"></div>
</div>  
<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
<div style="position: absolute; left: -5000px;"><input type="text" name="b_6e301501f8c1ac2241f7eb6c4_6e56d4a541" tabindex="-1" value=""></div>
<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
  </div>
</form>
</div>

<!--End mc_embed_signup-->



<!-- --------------------------------------------------------------------- -->  


<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">

<style type="text/css">
#mc_embed_signup{
background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; 
  width: 500px;
  display: block;
  margin-left: auto;
  margin-right: auto;
  /*border: 10px solid #ccc;
  border-radius: 25px;
  padding: 20px;
  padding-bottom: 10px;*/
}

body .modal {
  width: 500px;
  /* must be half of the width, minus scrollbar on the left (30px) */
  /* margin-left: -280px; */
  border: 10px solid #ccc;
  border-radius: 25px;
}
</style>

<!-- Button to trigger modal -->
<a href="#myModal2" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
 
<!-- Modal -->
<div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

<div class="modal-body">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<div id="mc_embed_signup">
<form action="//openrepgrid.us9.list-manage.com/subscribe/post?u=6e301501f8c1ac2241f7eb6c4&amp;id=6e56d4a541" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div id="mc_embed_signup_scroll">
<h2>Subscribe to our mailing list</h2>
<p style="color: #555; line-height: 150%;">Stay up to date with developments on OpenRepGrid. 
This is a low frequency list. There will be only very few mails per year.</p><br>
<div class="mc-field-group">
<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="email address">
</div>
<p><a href="http://us9.campaign-archive1.com/home/?u=6e301501f8c1ac2241f7eb6c4&id=6e56d4a541" title="View mail archive">View mail archive</a></p>
<div id="mce-responses" class="clear">
<div class="response" id="mce-error-response" style="display:none"></div>
<div class="response" id="mce-success-response" style="display:none"></div>
</div>    
<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
<div style="position: absolute; left: -5000px;"><input type="text" name="b_6e301501f8c1ac2241f7eb6c4_6e56d4a541" tabindex="-1" value=""></div>
<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</div>
</form>
</div>

  
</div>
<!-- <div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div> -->
</div>

<!--End mc_embed_signup-->


<!-- --------------------------------------------------------------------- -->  


<!-- Begin MailChimp Signup Form -->

<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
#mc_embed_signup {
  background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; 
}
</style>

<div id="mc_embed_signup">
<form action="//openrepgrid.us9.list-manage.com/subscribe/post?u=6e301501f8c1ac2241f7eb6c4&amp;id=6e56d4a541" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div id="mc_embed_signup_scroll">
<h2>Subscribe to our mailing list</h2>
<p style="color: #555; line-height: 150%;">Stay up to date with developments on OpenRepGrid. 
This is a low frequency list. There will be only very few mails per year.</p><br>
<div class="mc-field-group">
<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="email address">
</div>
<p><a href="http://us9.campaign-archive1.com/home/?u=6e301501f8c1ac2241f7eb6c4&id=6e56d4a541" title="View mail archive">View mail archive</a></p>
<div id="mce-responses" class="clear">
<div class="response" id="mce-error-response" style="display:none"></div>
<div class="response" id="mce-success-response" style="display:none"></div>
</div>    
<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
<div style="position: absolute; left: -5000px;"><input type="text" name="b_6e301501f8c1ac2241f7eb6c4_6e56d4a541" tabindex="-1" value=""></div>
<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</div>
</form>
</div>

<!--End mc_embed_signup-->